name: core_platform
version: "2.1.0"
config-version: 2

profile: "snowflake"
require-dbt-version: ">=1.6.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"

models:
  core_platform:
    # all models should have unique and not_null
    +required_tests: {"unique.*|not_null":2}
    staging:
      +materialized: view
    marts:
      +required_tests: {"relationship.*":1}
      +materialized: table

tests:
  core_platform:
    +severity: warn
    +store_failures: false
    +schema: failure
  